hash-format = "sha256"

[[files]]
file = "mods/enchanted-witchcraft.pw.toml"
hash = "bd2a4f57165695a15f63f7df4dc5fa48c3078ab8228c54ea6530bd49c66553a0"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "4851e08949034729ae5e108626ea4dea2221a66d6428167fc75e1ed59245bc05"
metafile = true

[[files]]
file = "mods/forge-config-api-port.pw.toml"
hash = "b898e0d94915287fcce4f85a3e5135e831475957e03d035ac05ecd7a7585929d"
metafile = true

[[files]]
file = "mods/geckolib.pw.toml"
hash = "4c7a1845fba5f6f245703a0644e18cefba81b87779377f1e31ed8ff9a18f729d"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "0e87ab10adb3db84b1d6d2ce8bdd7158878b56c965055056b10ad6cde2634568"
metafile = true

[[files]]
file = "mods/modopedia.pw.toml"
hash = "32d755d17bd4d01a562a00cd6a9ab285c60c8aaa735608ad2c99697ada5181d7"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "dd8c7eed10a3639d76595603142e1d18f6d26262747138c9442d70311006be5e"
metafile = true

[[files]]
file = "mods/stateobserver.pw.toml"
hash = "5e95bd67d0108d055c0aa09bfc071dd5e66c22b63d4a5c5fd805eaf40c7e3c7a"
metafile = true
